{
 "title": "Dshackle Stats 2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(dshackle_request_jsonrpc_err_total{},instance)"
    }
   },
   {
    "name": "chain",
    "query": {
     "query": "label_values(dshackle_upstreams_availability,chain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CHAIN:  $chain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "chain" },
  {
   "title": "Upstreams Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dshackle_upstreams_availability{instance=~\"$instance\", chain=~\"$chain\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Upstreams Lag",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "dshackle_upstreams_lag{instance=~\"$instance\", chain=~\"$chain\"}",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "JSON RPC total request / failed requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(dshackle_request_jsonrpc_request_total{chain=~\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(dshackle_request_jsonrpc_err_total{instance=~\"$instance\", chain=~\"$chain\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "GRPC total request / failed requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(dshackle_request_grpc_request_total{chain=~\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(dshackle_request_grpc_err_total{instance=~\"$instance\", chain=~\"$chain\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "JSON RPC OK requests by method",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(dshackle_request_jsonrpc_request_total{chain=~\"$chain\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "JSON RPC Error requests by method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(dshackle_request_jsonrpc_err_total{chain=~\"$chain\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "JSON RPC Failed requests by method",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(dshackle_request_jsonrpc_fail_total{chain=~\"$chain\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "JSON RPC Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(dshackle_request_jsonrpc_call_seconds_sum{chain=~\"$chain\",instance=~\"$instance\"}[1m]) / rate(dshackle_request_jsonrpc_call_seconds_count{chain=~\"$chain\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Upstreams Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(dshackle_upstream_rpc_err_total{chain=~\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "JSON RPC upstream conn seconds  50 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, dshackle_upstream_rpc_conn_seconds_bucket{instance=~\"$instance\",chain=~\"$chain\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "JSON RPC upstream conn seconds  75 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, dshackle_upstream_rpc_conn_seconds_bucket{instance=~\"$instance\",chain=~\"$chain\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "JSON RPC upstream conn seconds  90 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, dshackle_upstream_rpc_conn_seconds_bucket{instance=~\"$instance\",chain=~\"$chain\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "JSON RPC upstream conn seconds  99 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, dshackle_upstream_rpc_conn_seconds_bucket{instance=~\"$instance\",chain=~\"$chain\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "WS Upstreams Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(dshackle_upstream_ws_err_total{chain=~\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "WS upstream conn seconds  50 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, dshackle_upstream_ws_conn_seconds_bucket{instance=~\"$instance\",chain=~\"$chain\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "WS upstream conn seconds  75 percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, dshackle_upstream_ws_conn_seconds_bucket{instance=~\"$instance\",chain=~\"$chain\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Upstreams Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "dshackle_upstreams_lag{instance=~\"$instance\", chain=~\"$chain\"}",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Error Requests Total Count",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum by (method) (dshackle_request_jsonrpc_err_total{chain=~\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Failed Requests Total Count",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "sum by (method) (dshackle_request_jsonrpc_fail_total{chain=~\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "OK Requests Total Count",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "sum by (method) (dshackle_request_jsonrpc_request_total{chain=~\"$chain\", instance=~\"$instance\"})",
     "legendFormat": "{{ upstream }}"
    }
   ]
  }
 ]
}