= Dshackle Documentation

== What is Dshackle

Dshackle is an L7 Load Balancer for Blockchain APIs, equipped with features such as automatic discovery, health checking, secure access, and TLS with client authentication, among others.
It can be configured as an edge proxy, a middle proxy, or an API gateway.

Dshackle provides a high-level aggregated API that operates atop several underlying upstreams, including blockchain nodes or providers like Geth, Parity, Infura, etc.
It autonomously verifies their availability along with the current network status, routes requests to an available node, and ensures the responses are consistent and/or data is successfully broadcast across the network.

Example use cases:

- Query for a _transaction_ (block, etc) tries to find it on different nodes and/or retry until it's found or there is
a consistent answer from upstreams
- Getting _nonce_ to send a transaction makes sure it's larges value over several nodes
- Sending _transaction_ distributes it to several nodes in parallel

Availability and fault tolerance:

- Dshackle connects to several upstreams via JSON RPC, Websockets or gRPC protocols
- It verifies if a node ("upstream") is fully synchronized (not in initial sync mode), has enough peers and its height is not behind other nodes
- If an upstream lags behind, lost peers, started to resync, or simply goes down then Dshackle temporarily excludes it from routing and returns back when the upstream's problem is fixed

Main goals:

- stable and a fault tolerant access to blockchain nodes
- secure connections and authentication
- allow to build scalable APIs with nodes distributed over multiple data centers

== Table of Content

. link:01-architecture-intro.adoc[Architecture Overview]
. link:02-quick-start.adoc[Quick Start]
. link:03-server-config.adoc[Server Configuration]
. link:04-upstream-config.adoc[Upstreams Configuration]
. link:05-start.adoc[How to launch a server]
. link:06-monitoring.adoc[Logging & Monitoring]
. link:07-methods.adoc[API methods]
. link:08-authentication.adoc[Authentication]
. link:09-quorum-and-selectors.adoc[Quorum and Selectors]
. link:10-caching.adoc[Caching]
. link:11-client-libraries.adoc[Client Libraries]

== Reference

. link:reference-configuration.adoc[Configuration Reference]

== Chat

Join our Discord chat to discuss development and ask questions:

image:https://img.shields.io/discord/1107840420240707704?style=flat-square[Discord,link="https://discord.gg/k9HpF9Jqee"]

== Support

Contact splix@emerald.cash if you want to integrate Dshackle into your project or want to sponsor the development.

== Links

- Github: https://github.com/emeraldpay/dshackle