// Copyright 2026 EmeraldPay Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Protobuf encoding of cached values stored in Redis.
//!
//! The messages are generated at build time (see `build.rs`) from
//! `proto/cache.proto`, which mirrors the legacy schema — so values written
//! by this implementation can be read by a JVM Dshackle sharing the same
//! Redis and vice versa. This module wraps the generated types with
//! conversions to and from the cache containers.

use crate::data::{BlockContainer, BlockId, TxContainer, TxId};
use prost::Message;
use std::sync::Arc;

// Generated by prost-build from proto/cache.proto. GenericMeta is part of
// the schema but has no use here yet.
#[allow(dead_code)]
mod proto {
    include!(concat!(env!("OUT_DIR"), "/emerald.dshackle.rs"));
}

use proto::value_container::MetaType;
use proto::{BlockMeta, TxMeta, ValueContainer};

pub use proto::value_container::{Compression, ValueType};

/// Encode a block (with its raw JSON) for storage. Returns `None` when the
/// container carries no JSON — there is nothing worth caching then.
pub fn encode_block(block: &BlockContainer) -> Option<Vec<u8>> {
    let json = block.json.as_ref()?;
    let meta = BlockMeta {
        height: block.height,
        hash: block.hash.as_bytes().to_vec(),
        // Stored as a big-endian big integer, matching the legacy JVM cache.
        // A zero value is written as a single zero byte rather than empty
        // bytes, which the legacy reader rejects as an invalid big integer.
        difficulty: if block.total_difficulty.is_zero() {
            vec![0]
        } else {
            block.total_difficulty.to_be_bytes_trimmed_vec()
        },
        timestamp: block.timestamp.as_millisecond() as u64,
        tx_hashes: block
            .transaction_hashes
            .iter()
            .map(|t| t.as_bytes().to_vec())
            .collect(),
        parent_hash: block
            .parent_hash
            .map(|p| p.as_bytes().to_vec())
            .unwrap_or_default(),
    };
    let container = ValueContainer {
        r#type: ValueType::Block as i32,
        compression: Compression::None as i32,
        value: json.to_vec(),
        meta_type: Some(MetaType::BlockMeta(meta)),
    };
    Some(container.encode_to_vec())
}

pub fn decode_block(data: &[u8]) -> Option<BlockContainer> {
    let container = ValueContainer::decode(data).ok()?;
    if container.r#type != ValueType::Block as i32 {
        tracing::warn!(
            value_type = container.r#type,
            "unexpected value type for a cached block"
        );
        return None;
    }
    let Some(MetaType::BlockMeta(meta)) = container.meta_type else {
        return None;
    };

    Some(BlockContainer {
        hash: BlockId::from_bytes(meta.hash.try_into().ok()?),
        height: meta.height,
        parent_hash: id_from_bytes(meta.parent_hash).map(BlockId::from_bytes),
        total_difficulty: alloy::primitives::U256::try_from_be_slice(&meta.difficulty)
            .unwrap_or(alloy::primitives::U256::ZERO),
        timestamp: jiff::Timestamp::from_millisecond(meta.timestamp as i64).ok()?,
        transaction_hashes: meta
            .tx_hashes
            .into_iter()
            .map(|h| h.try_into().ok().map(TxId::from_bytes))
            .collect::<Option<Vec<_>>>()?,
        json: Some(Arc::from(container.value.as_slice())),
        // Cached blocks are full blocks; the newHeads egress reads header fields
        // from `json` when no standalone header was captured.
        header_json: None,
    })
}

/// Encode a transaction or a receipt (both are [`TxContainer`]s, see
/// [`CacheUpdate::Receipt`](super::caching_upstream::CacheUpdate::Receipt))
/// for storage.
pub fn encode_tx(tx: &TxContainer, value_type: ValueType) -> Option<Vec<u8>> {
    let json = tx.json.as_ref()?;
    let meta = TxMeta {
        height: tx.height.unwrap_or(0),
        hash: tx.hash.as_bytes().to_vec(),
        block_hash: tx
            .block_hash
            .map(|b| b.as_bytes().to_vec())
            .unwrap_or_default(),
    };
    let container = ValueContainer {
        r#type: value_type as i32,
        compression: Compression::None as i32,
        value: json.to_vec(),
        meta_type: Some(MetaType::TxMeta(meta)),
    };
    Some(container.encode_to_vec())
}

pub fn decode_tx(data: &[u8], expected: ValueType) -> Option<TxContainer> {
    let container = ValueContainer::decode(data).ok()?;
    if container.r#type != expected as i32 {
        tracing::warn!(
            value_type = container.r#type,
            expected = expected as i32,
            "unexpected value type for a cached transaction"
        );
        return None;
    }
    let Some(MetaType::TxMeta(meta)) = container.meta_type else {
        return None;
    };

    Some(TxContainer {
        hash: TxId::from_bytes(meta.hash.try_into().ok()?),
        block_hash: id_from_bytes(meta.block_hash).map(BlockId::from_bytes),
        // proto3 can't distinguish an absent height from 0; treating the
        // genesis block as "unknown height" is harmless for cached data
        height: (meta.height != 0).then_some(meta.height),
        json: Some(Arc::from(container.value.as_slice())),
    })
}

/// An optional 32-byte id is encoded as empty bytes when absent.
fn id_from_bytes(bytes: Vec<u8>) -> Option<[u8; 32]> {
    if bytes.is_empty() {
        return None;
    }
    bytes.try_into().ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_block() -> BlockContainer {
        BlockContainer {
            hash: BlockId::from_bytes([1u8; 32]),
            height: 100,
            parent_hash: Some(BlockId::from_bytes([2u8; 32])),
            total_difficulty: alloy::primitives::U256::ZERO,
            timestamp: jiff::Timestamp::from_millisecond(1_700_000_000_123).unwrap(),
            transaction_hashes: vec![TxId::from_bytes([3u8; 32]), TxId::from_bytes([4u8; 32])],
            json: Some(Arc::from(br#"{"number":"0x64"}"#.as_slice())),
            header_json: None,
        }
    }

    fn sample_tx() -> TxContainer {
        TxContainer {
            hash: TxId::from_bytes([3u8; 32]),
            block_hash: Some(BlockId::from_bytes([1u8; 32])),
            height: Some(100),
            json: Some(Arc::from(br#"{"hash":"0x03"}"#.as_slice())),
        }
    }

    #[test]
    fn block_roundtrip() {
        let block = sample_block();
        let data = encode_block(&block).unwrap();
        let decoded = decode_block(&data).unwrap();

        assert_eq!(decoded.hash, block.hash);
        assert_eq!(decoded.height, block.height);
        assert_eq!(decoded.parent_hash, block.parent_hash);
        assert_eq!(decoded.timestamp, block.timestamp);
        assert_eq!(decoded.transaction_hashes, block.transaction_hashes);
        assert_eq!(decoded.json.as_deref(), block.json.as_deref());
    }

    #[test]
    fn block_without_json_not_encoded() {
        let mut block = sample_block();
        block.json = None;
        assert!(encode_block(&block).is_none());
    }

    #[test]
    fn block_without_parent_roundtrip() {
        let mut block = sample_block();
        block.parent_hash = None;
        let data = encode_block(&block).unwrap();
        assert!(decode_block(&data).unwrap().parent_hash.is_none());
    }

    #[test]
    fn tx_roundtrip() {
        let tx = sample_tx();
        let data = encode_tx(&tx, ValueType::Tx).unwrap();
        let decoded = decode_tx(&data, ValueType::Tx).unwrap();

        assert_eq!(decoded.hash, tx.hash);
        assert_eq!(decoded.block_hash, tx.block_hash);
        assert_eq!(decoded.height, tx.height);
        assert_eq!(decoded.json.as_deref(), tx.json.as_deref());
    }

    #[test]
    fn receipt_roundtrip() {
        let receipt = sample_tx();
        let data = encode_tx(&receipt, ValueType::TxReceipt).unwrap();
        assert!(decode_tx(&data, ValueType::TxReceipt).is_some());
    }

    #[test]
    fn rejects_mismatched_type() {
        let block = sample_block();
        let tx = sample_tx();

        assert!(decode_block(&encode_tx(&tx, ValueType::Tx).unwrap()).is_none());
        assert!(decode_tx(&encode_block(&block).unwrap(), ValueType::Tx).is_none());
        assert!(
            decode_tx(
                &encode_tx(&tx, ValueType::Tx).unwrap(),
                ValueType::TxReceipt
            )
            .is_none()
        );
    }

    #[test]
    fn rejects_garbage() {
        assert!(decode_block(b"not a protobuf").is_none());
        assert!(decode_tx(b"not a protobuf", ValueType::Tx).is_none());
    }
}
