name: Tests

on:
  push:
    branches:
      - master
      - release/*
      - ci/*
  pull_request:
    branches:
      - master
      - release/*
      - ci/*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --release -- --nocapture
        env:
          RUST_BACKTRACE: "1"

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/xd009642/tarpaulin
      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Generate Code Coverage
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --release --no-fail-fast --out Lcov --output-dir ./coverage
          # coverage report is in ./coverage/lcov.info

      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Codecov
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

